apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-redis-container-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  redis.conf: |
    maxmemory 1000000000
    maxmemory-policy allkeys-lru